python demo
aliyun/serverless-function-compute-examples pull request #3
Opened 2019-09-18 05:06 UTC by yinglixn

2019-09-19 01:33 UTC, vangie requested changes

2019-09-19 01:33 UTC, vangie commented on aliyun_python/README
> +You can find the `aliyun_access_key_secret` and `aliyun_access_key_id` from https://ak-console.aliyun.com/?#/accesskey. You can also chose to create an Access Key or use sub-account Access Key.
chose => choose

2019-09-19 01:33 UTC, vangie commented on aliyun_python/serverless.yml
> +  credentials: ~/Workspace/aliyun-python/credentials # path must be absolute
这个位置感觉不太好，是这个 demo 特有的，我看其他 demo 是放在 ~/.aliyun_credentials，可以在多个 demo 中共享配置。

2019-09-19 01:34 UTC, vangie commented on aliyun_python/README
> +You can register and get your appcode from https://market.aliyun.com/products/57126001/cmapi014302.html. Then replace "<your app code>" with your code.
读到这里的时候稍微有些一些懵，最好前面介绍一下打算做一个天气查询的例子，预计会用到什么服务。

2019-09-19 23:04 UTC, yinglixn commented on aliyun_python/serverless.yml
> +  credentials: ~/Workspace/aliyun-python/credentials # path must be absolute
fixed

2019-09-19 23:04 UTC, yinglixn commented on aliyun_python/README
> +You can register and get your appcode from https://market.aliyun.com/products/57126001/cmapi014302.html. Then replace "<your app code>" with your code.
加了些描述

2019-09-19 23:04 UTC, yinglixn commented on aliyun_python/README
> +You can find the `aliyun_access_key_secret` and `aliyun_access_key_id` from https://ak-console.aliyun.com/?#/accesskey. You can also chose to create an Access Key or use sub-account Access Key.
fixed

2019-09-20 01:19 UTC, vangie approved these changes

2019-09-20 21:59 UTC, merged